# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pswd.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(541, 321)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 30, 441, 61))
        self.label.setStyleSheet("font: 75 20pt \"Rockwell\";")
        self.label.setObjectName("label")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(140, 130, 241, 31))
        self.btn.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.btn.setObjectName("btn")
        self.ansfield = QtWidgets.QLineEdit(Dialog)
        self.ansfield.setEnabled(True)
        self.ansfield.setGeometry(QtCore.QRect(60, 210, 401, 31))
        self.ansfield.setStyleSheet("font: 16pt \"Arial\";")
        self.ansfield.setReadOnly(True)
        self.ansfield.setObjectName("ansfield")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btn.clicked.connect(self.pswd_gen)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "STRONG PASSWORD GENERATOR"))
        self.btn.setText(_translate("Dialog", "Click here to get your password"))

    def len_exceeded(self,s,length_of_pswd):
        if len(s)>=length_of_pswd:
            return True
        return False

    def pswd_gen(self):
        length_of_pswd = randint(8,16)
        sm = "abcdefghijklmnopqrstuvwxyz"
        cap = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        num = "0123456789"
        sp_char = "$@#^&."
        pswd = ""
        while(len(pswd)<length_of_pswd):
            ran_num = randint(0,25)
            pswd+=sm[ran_num]
            if self.len_exceeded(pswd,length_of_pswd): break
            
            ran_num = randint(0,25)
            pswd+=cap[ran_num]
            if self.len_exceeded(pswd,length_of_pswd): break
            
            ran_num%=10
            pswd+=num[ran_num]
            if self.len_exceeded(pswd,length_of_pswd): break
            
            ran_num%=6
            pswd+=sp_char[ran_num]

        strng_pswd = list(pswd)
        shuffle(strng_pswd)
        self.ans = "".join(strng_pswd)
        self.ansfield.setText(str(self.ans))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
